
BAR_LENGTH = 4

FIRST = 0
SECOND = 2
THIRD = 4
FOURTH = 5
FIFTH = 7
SIXTH = 9
SEVENTH = 11
EIGHTH = 12
SCALE = [FIRST,SECOND,THIRD,FOURTH,FIFTH,SIXTH,SEVENTH,EIGHTH]
TWELVE_FORM = [FIRST, FOURTH, FIRST ,FIRST ,FOURTH,FOURTH, FIRST,FIRST ,FIFTH,FOURTH,FIRST,FIFTH]
EIGHT_FORM = [FIRST,FIRST,FIRST,FIRST,FOURTH,FOURTH,FIFTH,FIRST]
SIXTEEN_FORM = [FIRST,FIRST,FIRST,FIRST,FIRST,FIRST,FIRST,FIRST,FOURTH,FOURTH,FIRST,FIRST,FIFTH,FOURTH,FIRST,FIRST]